# Generated by Django 4.2.7 on 2023-11-09 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
