# Generated by Django 4.2.7 on 2023-11-09 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userentity_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentity',
            name='profile_picture',
        ),
    ]
