# Generated by Django 4.2.7 on 2023-11-10 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_userentity_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentity',
            name='phone_number',
        ),
    ]
