# Generated by Django 4.2.7 on 2023-11-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_userentity_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userentity',
            name='user',
        ),
    ]
