# Generated by Django 4.2.5 on 2023-11-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_sensordata_remove_userentity_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensordata',
            name='external_humidity',
        ),
        migrations.RemoveField(
            model_name='sensordata',
            name='external_temperature',
        ),
    ]
